version: '3'

services:
  mongo:
    image: mongo:4
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    links:
      - mongo

volumes:
  mongo-data:
